[package]
name = "draytek_imgtool"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
byteorder = "1.4"
clap = { version = "4.5", features = ["derive"] }
crc = "3.2"
md5 = "0.7"
parse_int = "0.6"
